model = "gpt-5-codex"
model_reasoning_effort = "medium"
[projects."/Users/pierrickmartino/Developer/blockbuilders.tech"]
trust_level = "trusted"

[mcp_servers.context7]
args = ["-y", "@upstash/context7-mcp", "--api-key", "ctx7sk-7b167dbc-5284-4af5-b51d-431a0818dc12"]
command = "npx"
startup_timeout_ms = 20_000

model = "gpt-5-codex"
model_reasoning_effort = "medium"
